/** Author-written developmental challenge set (not an untouched benchmark). Independent peer review is explicitly pending. */
import type { Attempt, Label } from "../lib/relearn/types.ts";
export type Case = {
  id: string;
  expected: Label | "unknown" | "ambiguous";
  attempt: Attempt;
};
function item(
  id: string,
  expected: Case["expected"],
  expression: string,
  answer: string,
  steps: string[],
  explanation: string,
): Case {
  return {
    id,
    expected,
    attempt: {
      id,
      createdAt: 0,
      problemId: "challenge",
      question:
        (expression.includes("=") ? "Solve " : "Simplify ") + expression,
      expression,
      answer,
      steps,
      explanation,
      probes: [],
    },
  };
}
export const challenge: Case[] = [
  item(
    "distribution-plain",
    "distribution",
    "4*(x+3)",
    "4x+3",
    ["4*x+3"],
    "Four goes with x; I keep the three as written.",
  ),
  item(
    "distribution-reordered",
    "distribution",
    "(5+x)*3",
    "5+3x",
    ["5+3*x"],
    "I used three on the letter and brought the five over without multiplying it.",
  ),
  item(
    "distribution-complex",
    "distribution",
    "2*(3*x+4)",
    "6x+4",
    ["2*3*x+4", "6x+4"],
    "I times the coefficient by two but the extra four is not part of that multiplication.",
  ),
  item(
    "product-pair-a",
    "negative_product",
    "-3*(x-4)",
    "-3x-12",
    ["(-3)*x+(-3)*(-4)", "-3x-12"],
    "I times minus three by each term. Minus three times minus four is minus twelve in my rule.",
  ),
  item(
    "product-short",
    "negative_product",
    "(-4)*(x-2)",
    "-4x-8",
    ["-4*x+(-4)*(-2)", "-4x-8"],
    "The constant is below zero because both multiplied numbers are below zero.",
  ),
  item(
    "product-typo",
    "negative_product",
    "-5*(x-3)",
    "-5x-15",
    ["(-5)*x+(-5)*(-3)", "-5x-15"],
    "I multipled every part; two negatives give a negative when you multiply them.",
  ),
  item(
    "scope-pair-b",
    "negative_scope",
    "-3*(x-4)",
    "-3x-12",
    ["-(3*x-12)", "-3x-12"],
    "I first made three x minus twelve. The minus out front turns three x negative; twelve keeps its sign.",
  ),
  item(
    "scope-single",
    "negative_scope",
    "-(x-7)",
    "-x-7",
    ["-x-7"],
    "I put the outside minus in front of x only. The minus seven already has a sign.",
  ),
  item(
    "scope-nested",
    "negative_scope",
    "-(2*x-8)",
    "-2x-8",
    ["-2x-8"],
    "Negating the bracket changes the first sign. I copied the remaining part without a sign change.",
  ),
  item(
    "unlike-plain",
    "unlike_terms",
    "5*x+4",
    "9x",
    ["(5+4)*x", "9x"],
    "I counted the four as four more x pieces, so there are nine of them.",
  ),
  item(
    "unlike-reordered",
    "unlike_terms",
    "7+2*x",
    "9x",
    ["(7+2)*x", "9x"],
    "The two numbers get added and I keep the variable at the end.",
  ),
  item(
    "unlike-three",
    "unlike_terms",
    "2*x+3*x+4",
    "9x",
    ["5*x+4", "9x"],
    "After collecting the five x parts I included four plain units in the coefficient.",
  ),
  item(
    "inverse-plain",
    "inverse",
    "x+4=10",
    "x=14",
    ["x=10+4", "x=14"],
    "I move four to the right with its plus sign unchanged.",
  ),
  item(
    "inverse-coefficient",
    "inverse",
    "3*x+5=17",
    "x=22/3",
    ["3*x=22", "x=22/3"],
    "I add five again to undo the plus five, and then divide both sides by three.",
  ),
  item(
    "inverse-transfer",
    "inverse",
    "6+x=15",
    "x=21",
    ["x=15+6", "x=21"],
    "I transfer the six over while keeping the addition operation.",
  ),
  item(
    "balance-plain",
    "balance",
    "x+4=10",
    "x=10",
    ["x=10"],
    "I took four off the left, and copied ten on the right without changing it.",
  ),
  item(
    "balance-coefficient",
    "balance",
    "3*x+5=17",
    "x=17/3",
    ["3*x=17", "x=17/3"],
    "Only the side with x needs work. I remove five there and leave seventeen alone.",
  ),
  item(
    "balance-transfer",
    "balance",
    "6+x=15",
    "x=15",
    ["x=15"],
    "Six can be erased from the variable side without a matching change on the other side.",
  ),
  item(
    "correct-expansion",
    "correct",
    "-3*(x-4)",
    "-3x+12",
    ["(-3)*x+(-3)*(-4)", "-3x+12"],
    "I multiply both terms by negative three. Two negative factors make a positive product.",
  ),
  item(
    "correct-equality",
    "correct",
    "2*x+5=13",
    "x=4",
    ["2*x=8", "x=4"],
    "Subtract five from each side, then divide each side by two to preserve the equality.",
  ),
  item(
    "correct-unlike",
    "correct",
    "2*x+4+3*x",
    "5x+4",
    ["5*x+4"],
    "The terms containing x share their variable part; the constant four remains separate.",
  ),
  item("ambiguous-answer-only", "ambiguous", "-2*(x-3)", "-2x-6", [], ""),
  item("ambiguous-no-reason", "ambiguous", "-2*(x-3)", "-2x-6", ["-2x-6"], ""),
  item(
    "ambiguous-guess",
    "ambiguous",
    "3*(x+4)",
    "3x+4",
    ["3x+4"],
    "I guessed.",
  ),
  item(
    "ambiguous-one-sided-answer",
    "ambiguous",
    "x+5=12",
    "x=12",
    [],
    "I do not remember how I decided.",
  ),
  item(
    "ambiguous-lucky",
    "ambiguous",
    "-2*(x-3)",
    "-2x+6",
    ["-2x-6", "-2x+6"],
    "I think two negatives multiply to a negative. I then changed the sign because I remembered the answer.",
  ),
  item(
    "ambiguous-conflict",
    "ambiguous",
    "3*(x+2)",
    "3x+6",
    ["3x+6"],
    "The outside multiplier only affects the first term. I copied a different final answer.",
  ),
  item(
    "unknown-fractions",
    "unknown",
    "x/2+x/3",
    "x/5",
    ["x/(2+3)", "x/5"],
    "I keep the top letter and add the bottom numbers when adding fractions.",
  ),
  item(
    "unknown-reversed-subtraction",
    "unknown",
    "3-8",
    "5",
    ["8-3", "5"],
    "I always take the smaller number away from the bigger one, regardless of their order.",
  ),
  item(
    "unknown-left-to-right",
    "unknown",
    "2+3*x",
    "5x",
    ["(2+3)*x", "5x"],
    "I follow every written operation from left to right, even before multiplication.",
  ),
  item(
    "unknown-roman-x",
    "unknown",
    "2*x+3",
    "23",
    ["2*10+3", "23"],
    "The letter x is the Roman numeral for ten, so I substituted ten.",
  ),
  item(
    "unknown-negative-addition",
    "unknown",
    "-4-3",
    "7",
    ["4+3", "7"],
    "I remove negative signs and add the sizes because two negatives make a positive.",
  ),
  item(
    "unknown-decimal",
    "unknown",
    "2.4+1.3",
    "37",
    ["24+13", "37"],
    "Decimal points are just separators; I erase them before adding.",
  ),
  item(
    "unknown-equal-means-add",
    "unknown",
    "x+4=10",
    "x=14",
    ["x=10+4", "x=14"],
    "The equals symbol tells me to add all the numbers written in the line.",
  ),
];
